//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabelSystemService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LabelToPrint
    {
        public int ID { get; set; }
        public string LabelText { get; set; }
        public string LabelType { get; set; }
        public string PrinterName { get; set; }
        public string CompletedLabelXML { get; set; }
        public Nullable<int> LabelPrinted { get; set; }
        public Nullable<System.DateTime> DateTimeEntered { get; set; }
        public Nullable<System.DateTime> DateTimePrinted { get; set; }
        public string ErrorInformation { get; set; }
    }
}
